### ISSUE TITLE
photoviewer@3.5.3 图片旋转90度后，放大缩小有问题

### ISSUE THREAD

**Issue by jin2gh** [nzbin/photoviewer#14]
版本：3.5.3，
问题：预览图片时，旋转 90 度或者 270 度，会导致只能缩小，正常角度、旋转180度的情况正常。

https://nzbin.github.io/photoviewer/ 预览时可复现
解决方案：版本3.4.0 正常

**Comment by nzbin** [comment]
这个问题是更新 `domq.js` 导致的，`v3.5.4` 已经修复。
