### ISSUE TITLE
Modal should be center w.r.t. the element in which its appended in, not w.r.t window 

### ISSUE THREAD

**Issue by sandgupta23** [nzbin/photoviewer#15]
First of all, awesome code and awesome library! Thank you for this! But I think I found a bug.

Pls see screenshot below. There is a problem with this code. Modal should be centered inside the element in which it is appeded. Not inside the window.

![image](https://user-images.githubusercontent.com/16303528/106325115-4b25f400-62a0-11eb-9752-24048dc1285e.png)

**Comment by nzbin** [comment]
`v3.6.0` has improved this issue.
