### ISSUE TITLE
image title error

### ISSUE THREAD

**Issue by ghost** [nzbin/photoviewer#18]
**image path: "/libs/img/flags/est/São Paulo.png"**

**RESULT:**
![2021-02-08_165311](https://user-images.githubusercontent.com/64440631/107273897-7510b080-6a2e-11eb-8f30-f1b289518bdd.png)

**Comment by nzbin** [comment]
Maybe there has some issues of get default image title. You can set image title manually.

```js
// build images array
var items = [
    {
        src: 'path/to/image1.jpg', // path to image
        title: 'Image Caption 1' // If you skip it, there will display the original image name(image1)
    },
    {
        src: 'path/to/image2.jpg',
        title: 'Image Caption 2'
    }
];
```

**Comment by ghost** [comment]
Hello!

I modified this function by adding **decodeURI**. Everything is working perfectly!

LINE 1377: photoviewer.js
```ruby
function getImageNameFromUrl(url) {
    var reg = /^.*?\/*([^/?]*)\.[a-z]+(\?.+|$)/gi;
    var txt = url.replace(reg, '$1');
    return decodeURI(txt);
}
```

Thanks!
