### ISSUE TITLE
When the viewer window is activated, the scroll bar of the background is frozen.

### ISSUE THREAD

**Issue by liqinan158** [nzbin/photoviewer#21]
Great work.

One minor comment: 
as the title suggests, when the viewer window is activated, the scroll bar of the background should still supposed to work if the wheel event is not happened within region of the activated window.

**Comment by nzbin** [comment]
Have you tried `fixedContent: false`?

**Comment by nzbin** [comment]
`v3.6.0` has removed `fixedContent` and enable page scrolling default.
