### ISSUE TITLE
With pagination, Photoviewer is getting initialized multiple times, hence opens multiple instance of photoviewer.

### ISSUE THREAD

**Issue by sanjeevkrready** [nzbin/photoviewer#28]
I am binding images with pagination on demand call. Hence, after each page change I need to initialize photoviewer with new set of items.  It looks like, after loading items on different page and initializing photoviewer, new instance of photoviewer  gets initialized as well as previous instance also exists. This opens multiple instance of same image in photoviewer on clicking once on image. 

I think, **on initializing again, there should be an option to destroy old instance** **_or_** there should be a way to update items in existing instance.

![Capture](https://user-images.githubusercontent.com/66209986/125204128-44f96200-e299-11eb-8f7f-eb12b72b3a69.PNG)

**Comment by nzbin** [comment]
Multiple instance is a feature of `Photoviewer` just like the behavior on Windows.
You can turn it off with option `multiInstances: false`.

**Comment by sanjeevkrready** [comment]
Worked like a charm!!! 
Thanks 👍
