### ISSUE TITLE
[Behavior] Image not centered while maximized or zoomed in.

### ISSUE THREAD

**Issue by PremiumHelp** [nzbin/photoviewer#3]
Hi, thanks @nzbin for this great plugin.

I have submitted this issue for [Behavior] only.

Clicking on image and popup display is correct,
but when zoomed out OR maximized, image is fixed floated to right edge, not **centered**.
(Works correctly outside of `<body>` )
please help me out, or suggest override styling.

Thank you.

**Comment by nzbin** [comment]
@PremiumHelp Can you give me a demo or screenshot?
