### ISSUE TITLE
Close popup When click outside and esc

### ISSUE THREAD

**Issue by shanmugamani96** [nzbin/photoviewer#34]
How to close the photo viewer popup when clicking the ESC button and clicking the outside popup?

**Comment by nzbin** [comment]
You can close the popup with the key `Q`.
You can't close the popup with clicking the outside because `photoviewer` is inspired by Windows Photo Viewer and very different from other lightbox.

**Comment by shanmugamani96** [comment]
how to change that key Q into esc,

**Comment by nzbin** [comment]
I am sorry that it doesn't support customize the key now.

**Comment by shanmugamani96** [comment]
hey, I changed the keycode 27 for close so it's working now,  but I need one option,I need to close the modal when clicking outside ,kindly add it,

**Comment by nzbin** [comment]
In fact, you can use any other popup library and embed the photoviewer into it.
Bootstrap modal example: https://codepen.io/nzbin/pen/rNdwOwy
