### ISSUE TITLE
RTL Bug

### ISSUE THREAD

**Issue by AliKhadivi** [nzbin/photoviewer#36]
Hi
I use ng-matero.
In RTL mode, the Photoviewer is fixed on the right and cannot be moved with the mouse.
![image](https://user-images.githubusercontent.com/74895885/185837884-b426a2df-3172-45ff-bdfe-20973b27da04.png)

**Comment by AliKhadivi** [comment]
![image](https://user-images.githubusercontent.com/74895885/185866470-c083ee94-d1b1-413e-bc51-67050ac046e1.png)
the perv and next button is reversed

**Comment by nzbin** [comment]
`v3.6.5` has fixed, you can have a try.
