### ISSUE TITLE
Arrows Prev and Next

### ISSUE THREAD

**Issue by TejaJsv** [nzbin/photoviewer#39]
photoviewer-button photoviewer-button-prev 
AND 
photoviewer-button photoviewer-button-next are not working for me can you please solve this issus in js

**Comment by nzbin** [comment]
Which version you used and can you give me an online example to test?

**Comment by TejaJsv** [comment]
photoviewer - v3.6.6

**Comment by TejaJsv** [comment]
i have used this example  - modal-init-maximized.html

**Comment by TejaJsv** [comment]
from git photoviewer git examples

**Comment by nzbin** [comment]
I'm sorry, I tested the example and I can't find any issues.

**Comment by TejaJsv** [comment]
ok Thank you
