### ISSUE TITLE
replace `data-src` but can not show the photo

### ISSUE THREAD

**Issue by leo493852107** [nzbin/photoviewer#4]
Hi nzbin,

Thanks for sharing.

I have meet a problem in steps2.

Way 2: Initializing as jQuery plugin

1.Using DOM structure is OK.

2. I want use this way:

`
<img data-gallery="jquery" data-src="big-1.jpg" src="small-1.jpg">
`

I have replace data-src and src with same jpeg, but I can see picture, click photo can not see it. Can you help me fix it?

Pls help check attached photo for details.

Thanks.

![image](https://user-images.githubusercontent.com/9987499/50595405-1b4a6d80-0edb-11e9-9997-c9566d119a0b.png)

**Comment by nzbin** [comment]
@leo493852107 If you use with jQuery, I hope you try the [Magnify](https://github.com/nzbin/magnify/).
Now the plugin has update to v3, it dosen't support jQuery any more.

**Comment by leo493852107** [comment]
> @leo493852107 If you use with jQuery, I hope you try the [Magnify](https://github.com/nzbin/magnify/).
> Now the plugin has update to v3, it dosen't support jQuery any more.

@nzbin Thanks, it worked with [Magnify](https://github.com/nzbin/magnify/).

**Comment by nzbin** [comment]
@leo493852107 🤝
