### ISSUE TITLE
Is there a way to dynamically add images after the plugin is initalized?

### ISSUE THREAD

**Issue by framesbyharsh** [nzbin/photoviewer#44]
Hi,
Good plugin however it seems there is no way to add a image once the plugin in initialized. I tried to hook into before open and then modify the file list but that did not worked.

Pls let me know if there is a way.

**Comment by nzbin** [comment]
You can use the `images` of the `photoviewer` instance to insert images.
I created an example https://codepen.io/nzbin/pen/abQPzpY, please check it.
