### ISSUE TITLE
pinch and zoom in mobile is not functional

### ISSUE THREAD

**Issue by kinizumi** [nzbin/photoviewer#46]
Unfortunately pinch and zoom in mobile is not functional, how come it can zoom in & out with scroll but not in mobile?
Move is not working neither in mobile unfortunately

**Comment by kinizumi** [comment]
never mind, this package is already very good!!!

**Comment by arielleshamash** [comment]
Is this a feature that is supposed to work? I've been trying but can't seem to get it @nzbin
