### ISSUE TITLE
photoviewer error while compiling angular

### ISSUE THREAD

**Issue by Ajaykumar661** [nzbin/photoviewer#50]
I am trying to run an angular project which has the dependency photoviewer, It used to work and recently I'm getting this error while compiling the angular project 

`ERROR in ./node_modules/photoviewer/src/js/core.js 35:19
Module parse failed: Unexpected token (35:19)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
| class PhotoViewer {
|   // Store modal instances
>   static instances = [];
|
|   // Whether modal opened
`

I tried upgrading/downgrading the version, nothing helped, Can someone please help on this?

TIA!

**Comment by nzbin** [comment]
Which Angular version do you use?

**Comment by Ajaykumar661** [comment]
Its Angular version 9

**Comment by nzbin** [comment]
The Angular 9 doesn't support JS class `static` prop, please try
```bash
npm i photoviewer@~3.8.0 -E
```

package.json
```json
{
  "dependencies": {
    ...
    "photoviewer": "~3.8.0",
    ...
  },
}
```

**Comment by Ajaykumar661** [comment]
Thanks ! that fixed the issue.
