### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by kausar007** [nzbin/photoviewer#51]
Hi,

First of all thanks for creating such a great plugin. I had always wanted to find something that resembles Windows photoviewer.

I have a couple of suggestion. Would you be able to introduce a dark mode that can be configured? 
The other suggestion is if we can make the icons at the footer a bit bigger or make the icon and title size configurable?

Thanks

**Comment by nzbin** [comment]
Many thanks for your advice, the photoviewer's style can be customized very easily. You can customize it as you like.
Please check this example https://codepen.io/nzbin/pen/dyLNBwg

In fact, I want to refactor the plugin in v4 and many new features will be there, but I'm not sure I have enough energy to finish it.

**Comment by kausar007** [comment]
Thanks for the quick response and sharing the codepen. I have managed to implement it on my project and also changed the size of icons by setting `font-size` css property of `photoviewer-button` class. Worked perfectly.
