### ISSUE TITLE
Can you make the crossorigin attribute dynamic or remove it?

### ISSUE THREAD

**Issue by Icoder9699** [nzbin/photoviewer#56]
Hi there! Can you please make the crossorigin attribute dynamic or remove it?

**Comment by nzbin** [comment]
May I ask what your problem is? Please check the PR #54 @souramoo

**Comment by Icoder9699** [comment]
> May I ask what your problem is? Please check the PR #54 @souramoo

When I use it across domains, the image doesn’t show up. Removing the crossorigin attribute from the <img> tag resolved the issue.

For more details: I'm trying to preview an image on a GitHub domain, but the image source is on another domain. In this case, I receive the following error:

Access to image at **X** from origin '**Y**' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by nzbin** [comment]
I'm sorry, I don't find issues on the demo site (https://nzbin.github.io/photoviewer/). It's a GitHub domain and the images are on flickr.

Can you give me a image URL which throwing error?

**Comment by Icoder9699** [comment]
> I'm sorry, I don't find issues on the demo site (https://nzbin.github.io/photoviewer/). It's a GitHub domain and the images are on flickr.
> 
> Can you give me a image URL which throwing error?

I have sent the link to you via email.

also I temporarily resolved this problem with an older version of the package. in 3.9.1 all is good

**Comment by nzbin** [comment]
Thanks for your advice, new version `3.10.3` has fixed.

**Comment by Icoder9699** [comment]
> Thanks for your advice, new version `3.10.3` has fixed.

Thank you for promptly resolving the issue!
