### ISSUE TITLE
zIndex not working

### ISSUE THREAD

**Issue by kuoruan** [nzbin/photoviewer#7]
Config of zIndex take no affects.

**Comment by nzbin** [comment]
@kuoruan can you give me a demo or describe it in more details

**Comment by kuoruan** [comment]
https://github.com/nzbin/photoviewer/blob/3923817dbcabf63561c1eae828c5cf6f859a520f/src/js/core.js#L223

This line set zIndex to ```PUBLIC_VARS['zIndex']``` which is default zIndex ```1090```, not the zIndex in config.

**Comment by nzbin** [comment]
@kuoruan It's certainly a bug, I will fix it tonight.
